require('plugins_config.telescope')
require('plugins_config.lualine')
require('plugins_config.dap')
require('plugins_config.tree-sitter')
require('plugins_config.mason')
-- require('plugins_config.oklch-color-picker')
require('plugins_config.blame')
